import { StyleSheet } from "react-native";
import Constants from "expo-constants";
import { Dimensions } from "react-native";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: "relative",
  },
  Map: {
    height: "100%",
  },
  indicator: {
    overflow: "hidden",
    width: "90%",
    borderRadius: 5,
    backgroundColor: "yellow",
    position: "absolute",
    zIndex: 1,
    top: 60,
    alignSelf: "center",
    height: 160,
  },
  square: {
    width: 15,
    height: 15,
  },
  wrap: {
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 5,
  },
  indText: {
    color: "black",
    marginLeft: 8,
    fontSize: 16,
    fontWeight: "bold",
  },
  floatbuttoncontainer: {
    position: "absolute",
    zIndex: 5,
    bottom: Constants.statusBarHeight,
    left: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  floatbutton: {
    width: 45,
    height: 45,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "black",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.2,
    elevation: 5,
    borderRadius: 40,
    marginBottom: 20,
  },
  modalcontainer: {
    left: 20,
    right: 20,
    bottom: 2 * Constants.statusBarHeight + windowHeight / 12,
    backgroundColor: "white",
    position: "absolute",
    shadowColor: "black",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.2,
    elevation: 5,
    borderRadius: 15,
    alignItems: "center",
    zIndex: 1,
    overflow: "hidden",
  },
  modaltextheader: {
    paddingVertical: 20,
    fontSize: 20,
    fontWeight: "bold",
  },
  modalchoicescontainer: {
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
  },
  modalchoice: {
    paddingVertical: 10,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    borderStyle: "solid",
    borderColor: "rgba(0,0,0,0.25)",
    borderWidth: 0.5,
  },
  parkingChoices: {
    width: "30%",
    textAlign: "center",
    fontSize: 16,
    fontWeight: "bold",
    color: "rgba(0,0,0,0.7)",
  },
  parkingAvailable: {
    width: "30%",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "bold",
  },
  choiceWrapper: {
    flexDirection: "row",
  },
  lastupdatetime: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1,
    alignItems: "center",
    flexDirection: "column-reverse",
  },
  lastupdatetext: {
    backgroundColor: "rgba(0,0,0,0.55)",
    borderRadius: 40,
    textAlign: "center",
    color: "white",
    paddingVertical: 5,
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  indicatorIcon: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  showInformation: {
    height: 120,
    flexDirection: "row",
    display: "flex",
  },
  LEFT: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  RIGHT: {
    flex: 2,
    backgroundColor: "#212121",
    justifyContent: "center",
    alignItems: "center",
  },
  infocontainer: {
    left: 20,
    right: 20,
    top: 230,
    backgroundColor: "white",
    position: "absolute",
    shadowColor: "black",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.2,
    elevation: 5,
    borderRadius: 15,
    alignItems: "center",
    zIndex: 1,
  },
  activityIndicator: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    zIndex: 6,
  },
  availableInformation: { fontSize: 80, fontWeight: "bold", color: "#00cc77" },
  informationSVGIcon: {
    position: "absolute",
    right: 10,
    top: 10,
  },
  parkingName: { color: "white", fontWeight: "bold", fontSize: 75 },
});
